/**
 * The pages that read the API, driven by responses the backend really gave.
 *
 * The fixtures under `backend/test/fixtures/` were recorded by
 * `npm run preview:capture` against a live backend, not written by hand — a
 * hand-authored one drifts from the API it describes exactly as these pages'
 * interfaces did. Backend tests already check the *field names* against them.
 * These check what a person actually sees, which is the half that text
 * matching cannot reach.
 */
import { describe, expect, test, vi, beforeEach, afterEach } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const FIX = join(__dirname, '..', '..', 'backend', 'test', 'fixtures')
const fixture = (n: string) => JSON.parse(readFileSync(join(FIX, `${n}.json`), 'utf8'))

/** Serve captured payloads through the module the pages actually call. */
function mockApi(routes: Record<string, unknown>) {
  vi.doMock('@/lib/apiFetch', () => ({
    apiFetch: vi.fn(async (path: string) => {
      const key = Object.keys(routes).find((r) => path.startsWith(r))
      if (!key) return { ok: false, status: 404, json: async () => ({}) }
      return { ok: true, status: 200, json: async () => routes[key] }
    }),
  }))
}

beforeEach(() => vi.resetModules())
afterEach(() => vi.doUnmock('@/lib/apiFetch'))

describe('dark pool', () => {
  test("renders the backend's own notice and disclaimer, verbatim", async () => {
    // The page used to display a hand-written "⚠ 24-HOUR DELAY" badge over
    // prints it had generated itself, while the two fields carrying the actual
    // regulatory language went unrendered.
    const body = fixture('darkpool')
    mockApi({ '/api/darkpool': body })
    const { default: Page } = await import('@/app/dark-pool/page')

    render(<Page />)
    await waitFor(() => expect(screen.getByText(body.notice)).toBeDefined())
    expect(screen.getByText(body.disclaimer)).toBeDefined()
  })

  test('marks simulated prints per row, and says so once at the top', async () => {
    const body = fixture('darkpool')
    // Every print in the capture is `source: 'simulation'` — no dark-pool feed
    // was configured. Wiring the endpoint did not make the page real, and it
    // must not read as though it did.
    expect(body.data.every((p: any) => p.source === 'simulation')).toBe(true)

    mockApi({ '/api/darkpool': body })
    const { default: Page } = await import('@/app/dark-pool/page')
    render(<Page />)

    await waitFor(() => expect(screen.getAllByText('SIMULATED').length).toBe(body.data.length))
    expect(screen.getByText(/generated by the backend, not observed/i)).toBeDefined()
  })

  test('an unreachable backend empties the table rather than filling it', async () => {
    vi.doMock('@/lib/apiFetch', () => ({
      apiFetch: vi.fn(async () => { throw new Error('connection refused') }),
    }))
    const { default: Page } = await import('@/app/dark-pool/page')
    render(<Page />)
    await waitFor(() => expect(screen.getByText(/Could not reach the backend/i)).toBeDefined())
    expect(screen.queryByText('SIMULATED')).toBeNull()
  })
})

describe('GEX chart', () => {
  test('shows the provenance of a real chain', async () => {
    const gex = fixture('gex')
    expect(gex.realData).toBe(true)
    mockApi({ '/api/gex': gex })
    const { GEXChart } = await import('@/components/gex/GEXChart')

    render(<GEXChart />)
    // `source` and `delayedMinutes` exist precisely so a delayed Cboe chain and
    // the synthetic fallback are not presented identically.
    await waitFor(() => expect(screen.getByText(/CBOE · 15MIN DELAYED/i)).toBeDefined())
  })

  test('draws nothing when the backend has no real chain', async () => {
    // The route's own comment: "a fabricated gamma flip looks exactly like a
    // real one". The chart used to invent one with Math.random either way.
    mockApi({ '/api/gex': { ...fixture('gex'), realData: false, source: 'synthetic' } })
    const { GEXChart } = await import('@/components/gex/GEXChart')

    render(<GEXChart />)
    await waitFor(() => expect(screen.getByText(/No gamma exposure available/i)).toBeDefined())
    expect(screen.getByText(/not drawn rather than drawn from a guess/i)).toBeDefined()
  })

  test('never labels a strike SUPPORT or RESISTANCE', async () => {
    // The backend does not classify strikes. The old table asserted one of
    // those two per row, chosen by `Math.random() > 0.5`.
    mockApi({ '/api/gex': fixture('gex') })
    const { GEXChart } = await import('@/components/gex/GEXChart')

    render(<GEXChart />)
    await waitFor(() => expect(screen.getByText(/LARGEST GAMMA EXPOSURE/i)).toBeDefined())
    expect(screen.queryByText(/SUPPORT/)).toBeNull()
    expect(screen.queryByText(/RESISTANCE/)).toBeNull()
  })

  test('reports the flip the backend computed', async () => {
    const gex = fixture('gex')
    mockApi({ '/api/gex': gex })
    const { GEXChart } = await import('@/components/gex/GEXChart')

    render(<GEXChart />)
    await waitFor(() => {
      expect(screen.getByText(new RegExp(`\\$${gex.flipStrike.toLocaleString()}`))).toBeDefined()
    })
  })
})
