/**
 * Research Workflow #1 — Options-Flow Competitor Intel
 *
 * Scans competitor platforms (FlowAlgo, CheddarFlow, Unusual Whales,
 * BlackBox Stocks) for current pricing and feature positioning, and
 * writes a dated markdown brief to reports/.
 *
 * Credit cost per run: ~4 scrapes + up to 2 searches (≈6 credits).
 *
 * Run:
 *   npx tsx scripts/research/competitor-intel.ts
 *
 * Rerun inputs:
 *   TARGETS        — edit the array below
 *   FIRECRAWL_API_KEY — required in env or .env
 */
import { mkdir, writeFile } from "node:fs/promises";
import { readFileSync } from "node:fs";
import path from "node:path";
import { FirecrawlClient, FirecrawlError } from "../../src/services/firecrawl/index.js";

interface Target {
  name: string;
  pricingUrl: string;
}

const TARGETS: Target[] = [
  { name: "FlowAlgo", pricingUrl: "https://www.flowalgo.com/pricing" },
  { name: "CheddarFlow", pricingUrl: "https://cheddarflow.com/pricing" },
  { name: "Unusual Whales", pricingUrl: "https://unusualwhales.com/pricing" },
  { name: "BlackBox Stocks", pricingUrl: "https://blackboxstocks.com/pricing" },
];

const OUT_DIR = path.resolve("reports");

async function main(): Promise<void> {
  loadDotEnv();
  const client = FirecrawlClient.fromEnv();
  const today = new Date().toISOString().slice(0, 10);

  const sections: string[] = [
    `# Options-Flow Competitor Intel — ${today}`,
    "",
    `> Generated by QuantFlow research workflow via Firecrawl. ` +
      `Source evidence cached under .firecrawl/ where applicable.`,
    "",
  ];

  for (const target of TARGETS) {
    process.stdout.write(`Scraping ${target.name} ... `);
    try {
      const data = await client.scrape(target.pricingUrl, {
        formats: ["markdown"],
        onlyMainContent: true,
      });
      const md = (data.markdown ?? "").trim();
      sections.push(
        `## ${target.name}`,
        ``,
        `- Source: ${target.pricingUrl}`,
        `- Fetched: ${new Date().toISOString()}`,
        `- Page title: ${data.metadata?.title ?? "n/a"}`,
        ``,
        md.length > 0 ? truncate(md, 4000) : "_No extractable content (possible JS wall or block)._",
        ``,
      );
      console.log(md.length > 0 ? `ok (${md.length} chars)` : "empty");
    } catch (err) {
      const msg = err instanceof FirecrawlError ? `${err.code}: ${err.message}` : String(err);
      sections.push(`## ${target.name}`, ``, `- Source: ${target.pricingUrl}`, `- **FAILED**: ${msg}`, ``);
      console.log(`FAILED — ${msg}`);
      if (err instanceof FirecrawlError && err.code === "INSUFFICIENT_CREDITS") {
        sections.push(`> Run aborted: Firecrawl account out of credits.`, ``);
        break;
      }
    }
  }

  sections.push(
    `---`,
    ``,
    `## Rerun inputs`,
    ``,
    "```",
    `command: npx tsx scripts/research/competitor-intel.ts`,
    `targets: ${TARGETS.map((t) => t.name).join(", ")}`,
    `env: FIRECRAWL_API_KEY`,
    "```",
    ``,
  );

  await mkdir(OUT_DIR, { recursive: true });
  const outPath = path.join(OUT_DIR, `competitor-intel-${today}.md`);
  await writeFile(outPath, sections.join("\n"), "utf8");
  console.log(`\nBrief written: ${outPath}`);
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max) + "\n\n_[truncated for brief — full content in cache]_";
}

/** Tiny .env loader — avoids a dotenv dependency. */
function loadDotEnv(): void {
  try {
    const raw = readFileSync(path.resolve(".env"), "utf8");
    for (const line of raw.split("\n")) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
      const key = m?.[1];
      const value = m?.[2];
      if (key && value !== undefined && !process.env[key]) {
        process.env[key] = value.trim();
      }
    }
  } catch {
    /* no .env — rely on process env */
  }
}

main().catch((err) => {
  console.error("competitor-intel failed:", err);
  process.exitCode = 1;
});
